/**
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp.reqLNG.impl;

import de.schneidertim.requirements.nlp.reqLNG.DomainObjectSynonym;
import de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Domain Object Synonym</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DomainObjectSynonymImpl extends ConceptOrSynonymImpl implements DomainObjectSynonym
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DomainObjectSynonymImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ReqLNGPackage.Literals.DOMAIN_OBJECT_SYNONYM;
  }

} //DomainObjectSynonymImpl
