/**
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp.reqLNG;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Actor Interaction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.schneidertim.requirements.nlp.reqLNG.ActorInteraction#getProvide <em>Provide</em>}</li>
 *   <li>{@link de.schneidertim.requirements.nlp.reqLNG.ActorInteraction#getThe1 <em>The1</em>}</li>
 *   <li>{@link de.schneidertim.requirements.nlp.reqLNG.ActorInteraction#getActor <em>Actor</em>}</li>
 *   <li>{@link de.schneidertim.requirements.nlp.reqLNG.ActorInteraction#getWith <em>With</em>}</li>
 *   <li>{@link de.schneidertim.requirements.nlp.reqLNG.ActorInteraction#getThe2 <em>The2</em>}</li>
 *   <li>{@link de.schneidertim.requirements.nlp.reqLNG.ActorInteraction#getAbility <em>Ability</em>}</li>
 *   <li>{@link de.schneidertim.requirements.nlp.reqLNG.ActorInteraction#getTo <em>To</em>}</li>
 * </ul>
 *
 * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getActorInteraction()
 * @model
 * @generated
 */
public interface ActorInteraction extends EObject
{
  /**
   * Returns the value of the '<em><b>Provide</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Provide</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Provide</em>' attribute.
   * @see #setProvide(String)
   * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getActorInteraction_Provide()
   * @model
   * @generated
   */
  String getProvide();

  /**
   * Sets the value of the '{@link de.schneidertim.requirements.nlp.reqLNG.ActorInteraction#getProvide <em>Provide</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Provide</em>' attribute.
   * @see #getProvide()
   * @generated
   */
  void setProvide(String value);

  /**
   * Returns the value of the '<em><b>The1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>The1</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>The1</em>' attribute.
   * @see #setThe1(String)
   * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getActorInteraction_The1()
   * @model
   * @generated
   */
  String getThe1();

  /**
   * Sets the value of the '{@link de.schneidertim.requirements.nlp.reqLNG.ActorInteraction#getThe1 <em>The1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>The1</em>' attribute.
   * @see #getThe1()
   * @generated
   */
  void setThe1(String value);

  /**
   * Returns the value of the '<em><b>Actor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Actor</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actor</em>' reference.
   * @see #setActor(Actor)
   * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getActorInteraction_Actor()
   * @model
   * @generated
   */
  Actor getActor();

  /**
   * Sets the value of the '{@link de.schneidertim.requirements.nlp.reqLNG.ActorInteraction#getActor <em>Actor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Actor</em>' reference.
   * @see #getActor()
   * @generated
   */
  void setActor(Actor value);

  /**
   * Returns the value of the '<em><b>With</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>With</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>With</em>' attribute.
   * @see #setWith(String)
   * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getActorInteraction_With()
   * @model
   * @generated
   */
  String getWith();

  /**
   * Sets the value of the '{@link de.schneidertim.requirements.nlp.reqLNG.ActorInteraction#getWith <em>With</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>With</em>' attribute.
   * @see #getWith()
   * @generated
   */
  void setWith(String value);

  /**
   * Returns the value of the '<em><b>The2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>The2</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>The2</em>' attribute.
   * @see #setThe2(String)
   * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getActorInteraction_The2()
   * @model
   * @generated
   */
  String getThe2();

  /**
   * Sets the value of the '{@link de.schneidertim.requirements.nlp.reqLNG.ActorInteraction#getThe2 <em>The2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>The2</em>' attribute.
   * @see #getThe2()
   * @generated
   */
  void setThe2(String value);

  /**
   * Returns the value of the '<em><b>Ability</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ability</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ability</em>' attribute.
   * @see #setAbility(String)
   * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getActorInteraction_Ability()
   * @model
   * @generated
   */
  String getAbility();

  /**
   * Sets the value of the '{@link de.schneidertim.requirements.nlp.reqLNG.ActorInteraction#getAbility <em>Ability</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ability</em>' attribute.
   * @see #getAbility()
   * @generated
   */
  void setAbility(String value);

  /**
   * Returns the value of the '<em><b>To</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>To</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' attribute.
   * @see #setTo(String)
   * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getActorInteraction_To()
   * @model
   * @generated
   */
  String getTo();

  /**
   * Sets the value of the '{@link de.schneidertim.requirements.nlp.reqLNG.ActorInteraction#getTo <em>To</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' attribute.
   * @see #getTo()
   * @generated
   */
  void setTo(String value);

} // ActorInteraction
