/**
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp.reqLNG;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Actor</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getActor()
 * @model
 * @generated
 */
public interface Actor extends Entity
{
} // Actor
