/**
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp.reqLNG;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Concept Or Synonym</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.schneidertim.requirements.nlp.reqLNG.ConceptOrSynonym#getName <em>Name</em>}</li>
 *   <li>{@link de.schneidertim.requirements.nlp.reqLNG.ConceptOrSynonym#getSynonyms <em>Synonyms</em>}</li>
 *   <li>{@link de.schneidertim.requirements.nlp.reqLNG.ConceptOrSynonym#getDescription <em>Description</em>}</li>
 * </ul>
 *
 * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getConceptOrSynonym()
 * @model
 * @generated
 */
public interface ConceptOrSynonym extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getConceptOrSynonym_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.schneidertim.requirements.nlp.reqLNG.ConceptOrSynonym#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Synonyms</b></em>' containment reference list.
   * The list contents are of type {@link de.schneidertim.requirements.nlp.reqLNG.ConceptOrSynonym}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Synonyms</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Synonyms</em>' containment reference list.
   * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getConceptOrSynonym_Synonyms()
   * @model containment="true"
   * @generated
   */
  EList<ConceptOrSynonym> getSynonyms();

  /**
   * Returns the value of the '<em><b>Description</b></em>' containment reference list.
   * The list contents are of type {@link de.schneidertim.requirements.nlp.reqLNG.SentenceWithReferences}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' containment reference list.
   * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getConceptOrSynonym_Description()
   * @model containment="true"
   * @generated
   */
  EList<SentenceWithReferences> getDescription();

} // ConceptOrSynonym
