/**
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp.reqLNG;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Domain Object Synonym</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getDomainObjectSynonym()
 * @model
 * @generated
 */
public interface DomainObjectSynonym extends ConceptOrSynonym
{
} // DomainObjectSynonym
