/**
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp.reqLNG;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Precondition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.schneidertim.requirements.nlp.reqLNG.Precondition#getConditional <em>Conditional</em>}</li>
 *   <li>{@link de.schneidertim.requirements.nlp.reqLNG.Precondition#getCondition <em>Condition</em>}</li>
 * </ul>
 *
 * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getPrecondition()
 * @model
 * @generated
 */
public interface Precondition extends EObject
{
  /**
   * Returns the value of the '<em><b>Conditional</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Conditional</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditional</em>' attribute.
   * @see #setConditional(String)
   * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getPrecondition_Conditional()
   * @model
   * @generated
   */
  String getConditional();

  /**
   * Sets the value of the '{@link de.schneidertim.requirements.nlp.reqLNG.Precondition#getConditional <em>Conditional</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conditional</em>' attribute.
   * @see #getConditional()
   * @generated
   */
  void setConditional(String value);

  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(TextWithReferences)
   * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getPrecondition_Condition()
   * @model containment="true"
   * @generated
   */
  TextWithReferences getCondition();

  /**
   * Sets the value of the '{@link de.schneidertim.requirements.nlp.reqLNG.Precondition#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(TextWithReferences value);

} // Precondition
