/**
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp.reqLNG;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Requirement End</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.schneidertim.requirements.nlp.reqLNG.RequirementEnd#getAi <em>Ai</em>}</li>
 *   <li>{@link de.schneidertim.requirements.nlp.reqLNG.RequirementEnd#getObjectWithDetails <em>Object With Details</em>}</li>
 * </ul>
 *
 * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getRequirementEnd()
 * @model
 * @generated
 */
public interface RequirementEnd extends EObject
{
  /**
   * Returns the value of the '<em><b>Ai</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ai</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ai</em>' containment reference.
   * @see #setAi(ActorInteraction)
   * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getRequirementEnd_Ai()
   * @model containment="true"
   * @generated
   */
  ActorInteraction getAi();

  /**
   * Sets the value of the '{@link de.schneidertim.requirements.nlp.reqLNG.RequirementEnd#getAi <em>Ai</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ai</em>' containment reference.
   * @see #getAi()
   * @generated
   */
  void setAi(ActorInteraction value);

  /**
   * Returns the value of the '<em><b>Object With Details</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Object With Details</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object With Details</em>' containment reference.
   * @see #setObjectWithDetails(TextWithConceptsOrSynonyms)
   * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getRequirementEnd_ObjectWithDetails()
   * @model containment="true"
   * @generated
   */
  TextWithConceptsOrSynonyms getObjectWithDetails();

  /**
   * Sets the value of the '{@link de.schneidertim.requirements.nlp.reqLNG.RequirementEnd#getObjectWithDetails <em>Object With Details</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object With Details</em>' containment reference.
   * @see #getObjectWithDetails()
   * @generated
   */
  void setObjectWithDetails(TextWithConceptsOrSynonyms value);

} // RequirementEnd
