/**
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp.reqLNG;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Requirement Document</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.schneidertim.requirements.nlp.reqLNG.RequirementDocument#getEntities <em>Entities</em>}</li>
 *   <li>{@link de.schneidertim.requirements.nlp.reqLNG.RequirementDocument#getRequirement <em>Requirement</em>}</li>
 *   <li>{@link de.schneidertim.requirements.nlp.reqLNG.RequirementDocument#getGlossary <em>Glossary</em>}</li>
 * </ul>
 *
 * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getRequirementDocument()
 * @model
 * @generated
 */
public interface RequirementDocument extends EObject
{
  /**
   * Returns the value of the '<em><b>Entities</b></em>' containment reference list.
   * The list contents are of type {@link de.schneidertim.requirements.nlp.reqLNG.Entity}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entities</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' containment reference list.
   * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getRequirementDocument_Entities()
   * @model containment="true"
   * @generated
   */
  EList<Entity> getEntities();

  /**
   * Returns the value of the '<em><b>Requirement</b></em>' containment reference list.
   * The list contents are of type {@link de.schneidertim.requirements.nlp.reqLNG.Requirement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Requirement</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Requirement</em>' containment reference list.
   * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getRequirementDocument_Requirement()
   * @model containment="true"
   * @generated
   */
  EList<Requirement> getRequirement();

  /**
   * Returns the value of the '<em><b>Glossary</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Glossary</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Glossary</em>' containment reference.
   * @see #setGlossary(Glossary)
   * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getRequirementDocument_Glossary()
   * @model containment="true"
   * @generated
   */
  Glossary getGlossary();

  /**
   * Sets the value of the '{@link de.schneidertim.requirements.nlp.reqLNG.RequirementDocument#getGlossary <em>Glossary</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Glossary</em>' containment reference.
   * @see #getGlossary()
   * @generated
   */
  void setGlossary(Glossary value);

} // RequirementDocument
