/**
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp.reqLNG;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unconditional Requirement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.schneidertim.requirements.nlp.reqLNG.UnconditionalRequirement#getThe <em>The</em>}</li>
 * </ul>
 *
 * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getUnconditionalRequirement()
 * @model
 * @generated
 */
public interface UnconditionalRequirement extends Requirement
{
  /**
   * Returns the value of the '<em><b>The</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>The</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>The</em>' attribute.
   * @see #setThe(String)
   * @see de.schneidertim.requirements.nlp.reqLNG.ReqLNGPackage#getUnconditionalRequirement_The()
   * @model
   * @generated
   */
  String getThe();

  /**
   * Sets the value of the '{@link de.schneidertim.requirements.nlp.reqLNG.UnconditionalRequirement#getThe <em>The</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>The</em>' attribute.
   * @see #getThe()
   * @generated
   */
  void setThe(String value);

} // UnconditionalRequirement
