/*
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp.parser.antlr;

import com.google.inject.Inject;
import de.schneidertim.requirements.nlp.parser.antlr.internal.InternalReqLNGParser;
import de.schneidertim.requirements.nlp.services.ReqLNGGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ReqLNGParser extends AbstractAntlrParser {

	@Inject
	private ReqLNGGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalReqLNGParser createParser(XtextTokenStream stream) {
		return new InternalReqLNGParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Entities";
	}

	public ReqLNGGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ReqLNGGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
