/*
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ReqLNGAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/schneidertim/requirements/nlp/parser/antlr/internal/InternalReqLNG.tokens");
	}
}
