/*
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ReqLNGRuntimeModule extends AbstractReqLNGRuntimeModule {
}
