/*
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp.ui.tests;

import com.google.inject.Injector;
import de.schneidertim.requirements.nlp.ui.internal.NlpActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class ReqLNGUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return NlpActivator.getInstance().getInjector("de.schneidertim.requirements.nlp.ReqLNG");
	}

}
