/**
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp.scoping;

import de.schneidertim.requirements.nlp.scoping.AbstractReqLNGScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ReqLNGScopeProvider extends AbstractReqLNGScopeProvider {
}
