/**
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp;

import de.schneidertim.requirements.nlp.AbstractReqLNGRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ReqLNGRuntimeModule extends AbstractReqLNGRuntimeModule {
}
