/**
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp;

import de.schneidertim.requirements.nlp.ReqLNGStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ReqLNGStandaloneSetup extends ReqLNGStandaloneSetupGenerated {
  public static void doSetup() {
    ReqLNGStandaloneSetup _reqLNGStandaloneSetup = new ReqLNGStandaloneSetup();
    _reqLNGStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
