/**
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp;

import com.google.inject.Binder;
import com.google.inject.binder.AnnotatedBindingBuilder;
import com.google.inject.binder.ScopedBindingBuilder;
import de.hsrm.cknauf.POSRegex.api.IPOSRegexPattern;
import de.hsrm.cknauf.POSRegex.impl.POSRegexPattern;
import de.schneidertim.requirements.nlp.AbstractReqLNGRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ReqLNGRuntimeModule extends AbstractReqLNGRuntimeModule {
  @Override
  public void configure(final Binder binder) {
    super.configure(binder);
    AnnotatedBindingBuilder<IPOSRegexPattern> _bind = binder.<IPOSRegexPattern>bind(IPOSRegexPattern.class);
    ScopedBindingBuilder _to = _bind.to(POSRegexPattern.class);
    _to.asEagerSingleton();
  }
}
