/**
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp.ui;

import de.schneidertim.requirements.nlp.ui.AbstractReqLNGUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ReqLNGUiModule extends AbstractReqLNGUiModule {
  public ReqLNGUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
