/**
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp.validation;

import de.schneidertim.requirements.nlp.validation.AbstractReqLNGValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ReqLNGValidator extends AbstractReqLNGValidator {
}
