/*
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp.tests

import com.google.inject.Inject
import de.schneidertim.requirements.nlp.reqLNG.Entities
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(ReqLNGInjectorProvider)
class ReqLNGParsingTest{

	@Inject
	ParseHelper<Entities> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
