/*
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp.tests

import com.google.inject.Inject
import de.schneidertim.requirements.nlp.reqLNG.RequirementDocument
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(ReqLNGInjectorProvider)
class ReqLNGParsingTest{

	@Inject
	ParseHelper<RequirementDocument> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Actor: Client
				Description: Some human user.
			 
			System:PrintServer
				Description: Some PrintServer.
			 
				The "PrintServer" will provide the "Client" with the ability to "print"  "documents".
			 
			System:HTTPServer
				Description: Some HTTP Server.
				The "HTTPServer" will provide the "Client" with the ability to "post a Document".
			 
			Glossary
				Object: document
				Synonyms: documents
			 
				Function:print
				Description: print a document.
				
				Function: post a Document
		''')
		Assert.assertNotNull(result)
	}

}
