/*
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp.serializer;

import com.google.inject.Inject;
import de.schneidertim.requirements.nlp.services.ReqLNGGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class ReqLNGSyntacticSequencer extends AbstractSyntacticSequencer {

	protected ReqLNGGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Function___DescriptionKeyword_4_0_ColonKeyword_4_1__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (ReqLNGGrammarAccess) access;
		match_Function___DescriptionKeyword_4_0_ColonKeyword_4_1__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getFunctionAccess().getDescriptionKeyword_4_0()), new TokenAlias(false, false, grammarAccess.getFunctionAccess().getColonKeyword_4_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Function___DescriptionKeyword_4_0_ColonKeyword_4_1__q.equals(syntax))
				emit_Function___DescriptionKeyword_4_0_ColonKeyword_4_1__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('Description' ':')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=Text (ambiguity) (rule end)
	 *     synonyms+=FunctionSynonym (ambiguity) (rule end)
	 */
	protected void emit_Function___DescriptionKeyword_4_0_ColonKeyword_4_1__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
