/**
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp.ui.contentassist;

import de.schneidertim.requirements.nlp.ui.contentassist.AbstractReqLNGProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ReqLNGProposalProvider extends AbstractReqLNGProposalProvider {
}
