/**
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp.tests;

import com.google.inject.Inject;
import de.schneidertim.requirements.nlp.tests.ReqLNGInjectorProvider;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(ReqLNGInjectorProvider.class)
@SuppressWarnings("all")
public class ReqLNGParsingTest {
  @Inject
  private /* ParseHelper<Entities> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field ReqLNGParsingTest.parseHelper refers to the missing type Entities");
  }
}
