/*
 * generated by Xtext 2.10.0
 */
package de.schneidertim.requirements.nlp.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractReqLNGScopeProvider extends DelegatingScopeProvider {
}
